name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: senturkengin/scratch_proj@master
      with:
        url: "http://hqmsslwks205.maxim-ic.com:8080/job/Github_Test/"
        user: "engin.senturk"
        token: ${{ secrets.11b87a4c9aa2f1e6f3bdc72ef13d75e038 }}
        job: "Github_Test"
        
        
